#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD socket server
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_ARGS="-d"

start() {
	printf "Starting aesdsocket: "
	start-stop-daemon -S -n aesdsocket -a "$DAEMON" -- $DAEMON_ARGS
	RET=$?
	if [ $RET -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return $RET
}

stop() {
	printf "Stopping aesdsocket: "
	# Send SIGTERM so the app can cleanup (/var/tmp/aesdsocketdata removal)
	start-stop-daemon -K -s TERM -n aesdsocket
	RET=$?
	if [ $RET -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return $RET
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
	esac

exit $?
